name: main
on:
  push:
    branches:
    - main
    tags:
    - "*"
  pull_request:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        set-safe-directory: true
        fetch-depth: 0
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.1
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Archive release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: baebg2
          path: baebg2
  release:
    needs: [pre-commit, build]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4.3.1
        id: git-cliff
        with:
          config: cliff.toml
          args: --latest -o CHANGELOG.md
      - name: Print the changelog
        run: cat CHANGELOG.md
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.14.0
        with:
          bodyFile: ./CHANGELOG.md
          skipIfReleaseExists: True
